exports.models = [
    {
        name: 'gemini-1.5-flash',
        displayName: 'Gemini 1.5 Flash',
        baseURL: 'https://generativelanguage.googleapis.com/v1beta/',
        description: 'A high-performance model with advanced reasoning capabilities.',
        provider: 'Google',
    },
    {
        name: 'gemini-2.0-flash-lite',
        displayName: 'Gemini 2.0 Flash Lite',
        baseURL: 'https://generativelanguage.googleapis.com/v1beta/',
        description: 'A lightweight version of Gemini 2.0 Flash, optimized for speed and efficiency.',
        provider: 'Google',
    },
    {
        name: 'gemini-2.0-flash',
        displayName: 'Gemini 2.0 Flash',
        baseURL: 'https://generativelanguage.googleapis.com/v1beta/',
        description: 'A robust model designed for handling complex and demanding tasks.',
        provider: 'Google',
    },
    {
        name: 'gemini-2.5-flash-preview-05-20',
        displayName: 'Gemini 2.5 Flash Preview',
        baseURL: 'https://generativelanguage.googleapis.com/v1beta/',
        description: 'A preview version of Gemini 2.5 Flash, optimized for fast and efficient tasks.',
        provider: 'Google',
    },
    {
        name: 'meta-llama/llama-4-maverick-17b-128e-instruct',
        displayName: 'Llama 4 Maverick 17B Instruct',
        baseURL: 'https://api.groq.com/openai/v1',
        description: 'An advanced instruction-based model with enhanced capabilities.',
        provider: 'Groq',
    },
    {
        name: 'qwen-qwq-32b',
        displayName: 'Qwen QWQ 32B',
        baseURL: 'https://api.groq.com/openai/v1',
        description: 'A powerful model with 32 billion parameters for diverse tasks.',
        provider: 'Groq',
    },
    {
        name: 'deepseek-r1-distill-llama-70b',
        displayName: 'DeepSeek R1 Distill Llama 70B',
        baseURL: 'https://api.groq.com/openai/v1',
        description: 'A distilled version of Llama 70B, designed for high performance.',
        provider: 'Groq',
    },
    {
        name: 'llama-3.1-8b-instant',
        displayName: 'Llama 3.1 8B Instant',
        baseURL: 'https://api.groq.com/openai/v1',
        description: 'A compact and fast model with 8 billion parameters for instant results.',
        provider: 'Groq',
    },
    {
        name: 'gemma2-9b-it',
        displayName: 'Gemma 2 9B IT',
        baseURL: 'https://api.groq.com/openai/v1',
        description: 'A specialized model for IT-related tasks with 9 billion parameters.',
        provider: 'Groq',
    },
];
